version: "3.9"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  home_page:
    build:
      context: ./home_page
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydb
    ports:
      - "8081:8080"

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydb
    depends_on:
      home_page:
        condition: service_healthy
    ports:
      - "8082:8080"

  llm_chat:
    build:
      context: ./llm_chat
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydb
    depends_on:
      home_page:
        condition: service_healthy
    ports:
      - "8083:8080"

volumes:
  pgdata:
